#! /bin/bash
#---------------------------------------------------------------------
# Link the current versions into ~/apps/dirhistory/

ln -fv cd.sh ~/apps/dirhistory/cd.sh
ln -fv dirchange ~/apps/dirhistory/dirchange
ln -fv dirhistoryd ~/apps/dirhistory/dirhistoryd
ln -fv dirpick ~/apps/dirhistory/dirpick
